### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/penguin-watch-fb#8]
When building:

```
Step 9 : RUN npm run build-facebook
 ---> Running in 936e9987c940

> penguins@0.0.1 build-facebook /app
> node preflight-set-facebook-env.js && npm run build


/app/preflight-set-facebook-env.js:7
var TEMPLATE = `module.exports = '${ENV}'`;
               ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

npm ERR! Linux 4.4.20-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-facebook"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! penguins@0.0.1 build-facebook: `node preflight-set-facebook-env.js && npm run build`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the penguins@0.0.1 build-facebook script 'node preflight-set-facebook-env.js && npm run build'.
npm ERR! This is most likely a problem with the penguins package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node preflight-set-facebook-env.js && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs penguins
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls penguins
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
The command '/bin/sh -c npm run build-facebook' returned a non-zero code: 1
```

**Comment by rogerhutchings** [comment]
Thanks @astopy, this should be fixed via bf178a7
